---
name: assigned_open_issues_database_cache
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/57108
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/325470
group: group::product planning
type: development
default_enabled: false
