---
name: cached_issuables_state_count
introduced_by_url:
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/333089
milestone: '14.1'
type: development
group: group::product planning
default_enabled: false
