---
name: ci_jobs_trace_size_limit
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/65349
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/335259
milestone: '14.1'
type: development
group: group::pipeline execution
default_enabled: false
