---
name: codequality_mr_diff_annotations
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/57926
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/330909
milestone: '14.0'
type: development
group: group::testing
default_enabled: false
