---
name: evalute_protected_tag_for_release_permissions
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/64693
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/334368
milestone: '14.1'
type: development
group: group::release
default_enabled: false
