---
name: migrate_environment_details_to_vue
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/57055
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/325495
milestone: '13.11'
type: development
group: group::threat insights
default_enabled: false
