---
name: unlink_dependency_proxy_tempfiles
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/65676
rollout_issue_url: 
milestone: '14.1'
type: development
group: group::package
default_enabled: false
