---
name: vue_ref_dropdown
introduced_by_url:
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/330409
milestone: '13.12'
type: development
group: group::source code
default_enabled: false
