---
name: geo_upload_replication
introduced_by_url:
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/270449
milestone: '14.1'
type: development
group: group::geo
default_enabled: false
