---
name: jira_issue_association_on_merge_request
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/52896
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/300271
milestone: '13.9'
type: development
group: group::compliance
default_enabled: true
