---
name: security_orchestration_policies_configuration
introduced_by_url:
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/300918
milestone: '13.10'
type: development
group: group::container security
default_enabled: false
