# frozen_string_literal: true

require 'set'

module Gitlab
  module ErrorTracking
    module Processor
      class ContextPayloadProcessor < ::Raven::Processor
        # This processor is added to inject application context into Sentry
        # events generated by Sentry built-in integrations. When the
        # integrations are re-implemented and use Gitlab::ErrorTracking, this
        # processor should be removed.
        def process(payload)
          context_payload = Gitlab::ErrorTracking::ContextPayloadGenerator.generate(nil, {})
          context_payload.merge!(payload)
        end
      end
    end
  end
end
