---
data_category: Optional
key_path: usage_activity_by_stage_monthly.manage.projects_with_compliance_framework
description:
product_section: dev
product_stage:
product_group: group::manage
product_category:
value_type: number
status: data_available
time_frame: 28d
data_source:
distribution:
- ee
tier: []
skip_validation: true
