---
data_category: Optional
key_path: usage_activity_by_stage_monthly.plan.milestone_lists
description: Count of MAU created milestone lists on Boards 
product_section: dev
product_stage: plan 
product_group: group::project management 
product_category: boards 
value_type: number
status: data_available
time_frame: 28d
data_source: database 
distribution:
- ee 
tier:
- premium 
- ultimate 
