---
data_category: Optional
key_path: redis_hll_counters.analytics.g_analytics_contribution_monthly
description: Unique visitors to /groups/:group/-/contribution_analytics by month
product_section: dev
product_stage: manage
product_group: group::optimize
product_category:
value_type: number
status: data_available
time_frame: 28d
data_source: redis_hll
distribution:
- ce
tier:
- free
skip_validation: true
