---
data_category: Optional
key_path: redis_hll_counters.epic_boards_usage.epic_boards_usage_total_unique_counts_monthly
name: "0"
description:
product_section:
product_stage:
product_group:
product_category:
value_type: number
status: data_available
milestone: "13.12"
introduced_by_url:
time_frame: 28d
data_source:
distribution:
- ee
tier:
#- premium
- ultimate
skip_validation: true
