---
data_category: Optional
key_path: redis_hll_counters.ecosystem.i_ecosystem_jira_service_create_issue_monthly
description: Number of users creating Jira issues by month
product_section: dev
product_stage: create
product_group: group::ecosystem
product_category: integrations
value_type: number
status: data_available
time_frame: 28d
data_source: redis_hll
distribution:
- ee
tier:
- premium
- ultimate
