---
data_category: Optional
key_path: counts.releases
description: Unique release tags
product_section: ops
product_stage:
product_group: group::release
product_category:
value_type: number
status: data_available
time_frame: all
data_source: database
distribution:
- ce
tier:
- free
skip_validation: true
