---
data_category: Optional
key_path: counts.successful_deployments
description: Total successful deployments
product_section: ops
product_stage:
product_group: group::release
product_category:
value_type: number
status: data_available
time_frame: all
data_source: database
distribution:
- ce
tier:
- free
skip_validation: true
