---
data_category: Optional
key_path: redis_hll_counters.ide_edit.ide_edit_total_unique_counts_weekly
description: Weekly number of users editing a file using the Web IDE
product_section: dev
product_stage: create
product_group: group::editor
product_category: web_ide
value_type: number
status: data_available
time_frame: 7d
data_source: redis_hll
distribution:
- ce
- ee
tier:
- free
- premium
- ultimate
