---
data_category: Optional
key_path: redis_hll_counters.ecosystem.i_ecosystem_jira_service_cross_reference_weekly
description: Number of users that cross-referenced Jira issues by week
product_section: dev
product_stage: create
product_group: group::ecosystem
product_category: integrations
value_type: number
status: data_available
time_frame: 7d
data_source: redis_hll
distribution:
- ce
- ee
tier:
- free
- premium
- ultimate
