#!/usr/bin/env ruby

require_relative '../lib/gitlab/popen'
require_relative '../lib/quality/test_file_finder'

output_file = ARGV.shift

source = ENV.fetch('CI_MERGE_REQUEST_SOURCE_BRANCH_NAME')
target = ENV.fetch('CI_MERGE_REQUEST_TARGET_BRANCH_NAME')

git_diff = Gitlab::Popen.popen_with_detail(%w[git diff --name-only] + ["origin/#{target}...origin/#{source}"])

unless git_diff.status.success?
  warn "**** #{git_diff.cmd.join(' ')} had the following error(s):"
  warn git_diff.stderr
  exit git_diff.status.exitstatus
end

changed_files = git_diff.stdout.split("\n")

tests_to_run = changed_files.flat_map do |file|
  test_files = Quality::TestFileFinder.new(file, foss_test_only: true).test_files
  test_files.select { |f| File.exist?(f) }
end

File.write(output_file, tests_to_run.uniq.join(' '))
