export const mockIssueLink = {
  assignee: null,
  assignees: [],
  author: { id: 1, name: 'Administrator', username: 'container', state: 'active' },
  blocking_issues_count: 0,
  closed_at: null,
  closed_by: null,
  confidential: true,
  created_at: '2021-01-10T23:17:23.385Z',
  description: 'description',
  discussion_locked: null,
  downvotes: 0,
  due_date: null,
  id: 501,
  iid: 12,
  labels: [],
  merge_requests_count: 0,
  milestone: null,
  project_id: 23,
  state: 'opened',
  task_completion_status: { count: 0, completed_count: 0 },
  time_stats: {
    time_estimate: 0,
    total_time_spent: 0,
    human_time_estimate: null,
    human_total_time_spent: null,
  },
  title: 'Investigate vulnerability: Improper Input Validation in xterm',
  updated_at: '2021-01-10T23:17:23.385Z',
  upvotes: 0,
  user_notes_count: 0,
  vulnerability_link_id: 53,
  vulnerability_link_type: 'created',
  web_url: 'http://gdk.test:3000/security-reports/dependency-list-test/-/issues/12',
  weight: null,
};
