---
data_category: Optional
key_path: redis_hll_counters.analytics.g_analytics_valuestream_weekly
description: Unique visitors to /groups/:group/-/analytics/value_stream_analytics by week
product_section: dev
product_stage: manage
product_group: group::optimize
product_category:
value_type: number
status: data_available
time_frame: 7d
data_source: redis_hll
distribution:
- ee
tier: []
skip_validation: true
