---
data_category: Optional
key_path: redis_hll_counters.epics_usage.g_project_management_users_awarding_epic_emoji_weekly
description: Counts of WAU awarding emoji on epic
product_section: dev
product_stage: plan
product_group: group::product planning
product_category: epics_usage
value_type: number
status: data_available
milestone: "13.12"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/60787
time_frame: 28d
data_source: redis_hll
distribution:
- ee
tier:
- premium
- ultimate
