---
data_category: Optional
key_path: redis_hll_counters.ide_edit.ide_edit_total_unique_counts_monthly
description: Count of unique users per month who edited a file from the Web IDE
product_section: dev
product_stage: create
product_group: group::editor
product_category: web_ide
value_type: number
status: data_available
time_frame: 28d
data_source: redis_hll
distribution:
- ce
- ee
tier:
- free
- premium
- ultimate
