---
data_category: Optional
key_path: redis_hll_counters.quickactions.i_quickactions_unlabel_all_monthly
description: Count of MAU using the `/unlabel` quick action to remove all labels
product_section: dev
product_stage: plan
product_group: group::project management
product_category: issue_tracking
value_type: number
status: data_available
time_frame: 28d
data_source: redis_hll
distribution:
- ce
- ee 
tier:
- free
- premium 
- ultimate
