---
data_category: Optional
key_path: counts_monthly.failed_deployments
description: Total failed deployments
product_section: ops
product_stage:
product_group: group::release
product_category:
value_type: number
status: data_available
time_frame: 28d
data_source: database
distribution:
- ce
tier:
- free
skip_validation: true
