---
data_category: Optional
key_path: usage_activity_by_stage_monthly.manage.unique_users_all_imports
description: Number of users from projects imported
product_section: dev
product_stage: manage
product_group: group::import
product_category: ''
value_type: number
status: data_available
time_frame: 28d
data_source: database
distribution:
- ce
- ee
tier:
- free
- premium
- ultimate
