---
key_path: redis_hll_counters.analytics.g_analytics_valuestream_monthly
description:
product_section: dev
product_stage: manage
product_group: group::analytics
product_category:
value_type: number
status: data_available
time_frame: 28d
data_source: redis_hll
instrumentation_class: 'Gitlab::Usage::Metrics::Instrumentations::CountUsersVisitingAnalyticsValuestreamMetric'
distribution:
- ce
tier:
- free
skip_validation: true
