---
data_category: Optional
key_path: redis_hll_counters.quickactions.quickactions_total_unique_counts_monthly
description: Count of MAU using one or more quick actions
product_section: dev
product_stage: plan 
product_group: group::project management 
product_category: issue_tracking 
value_type: number
status: data_available
time_frame: 28d
data_source: redis_hll
distribution:
- ce
- ee 
tier:
- free
- premium
- ultimate 
