---
name: prometheus_metrics_measure_geo_reset_syncs_since_gc_cpu_duration
introduced_by_url: https://gitlab.com/gitlab-org/gitlab-foss/-/merge_requests/16443
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/326202
milestone: '10.5'
type: ops
group: group::monitor
default_enabled: false
