.compress-public: &compress-public
  - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|json\|css\|svg\|xml\)$' -exec gzip -f -k {} \;
  - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|json\|css\|svg\|xml\)$' -exec brotli -f -k {} \;

pages:
  extends:
    - .default-retry
    - .pages:rules
  stage: pages
  needs:
    - rspec:coverage
    - coverage-frontend
    - karma
    - compile-production-assets
    - compile-storybook
  before_script:
    - apt-get update && apt-get -y install brotli gzip
  script:
    - mv public/ .public/
    - mkdir public/
    - mv coverage/ public/coverage-ruby/ || true
    - mv coverage-frontend/ public/coverage-frontend/ || true
    - mv coverage-javascript/ public/coverage-javascript/ || true
    - mv storybook/public public/storybook || true
    - cp .public/assets/application-*.css public/application.css || true
    - *compress-public
  artifacts:
    paths:
      - public
    expire_in: 31d
