---
data_category: Optional
key_path: counts.kubernetes_agent_k8s_api_proxy_request
description: Count of Kubernetes API proxy requests
product_section: ops
product_stage: configure
product_group: group::configure
product_category: kubernetes_management
value_type: number
status: data_available
milestone: "13.12"
introduced_by_url:
time_frame: all
data_source: redis
distribution:
- ee
tier:
- premium
- ultimate
