---
data_category: Optional
key_path: analytics_unique_visits.p_analytics_issues
description: Unique visitors to /:group/:project/-/analytics/issues_analytics
product_section: dev
product_stage: manage
product_group: group::optimize
product_category:
value_type: number
status: data_available
time_frame: all
data_source:
distribution:
- ce
tier:
- free
skip_validation: true
