---
data_category: Optional
key_path: usage_activity_by_stage_monthly.monitor.projects_incident_sla_enabled
description: Count of projects with Incident SLA enabled
product_section: ops
product_stage:
product_group: group::monitor
product_category: metrics
value_type: number
status: data_available
time_frame: all
data_source: database
distribution:
  - ee
tier:
  - premium
  - ultimate
